export const images=[
    require('../../assets/images/f1.jpg'),
     require('../../assets/images/f2.jpg'),
     require('../../assets/images/f3.jpg'),
     require('../../assets/images/f4.webp'),
     require('../../assets/images/f5.jpg'),
     require('../../assets/images/f6.jpg'),
     require('../../assets/images/f7.jpg'),
     require('../../assets/images/f8.jpg'),
     require('../../assets/images/f9.jpg'),
     require('../../assets/images/f10.jpg'),
     require('../../assets/images/f11.jpg'),
     require('../../assets/images/f12.jpg'),
     require('../../assets/images/f13.webp'),
     require('../../assets/images/f3.jpg'),
     require('../../assets/images/f4.webp'),
     require('../../assets/images/f5.jpg'),
     require('../../assets/images/f6.jpg')
]